/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
        "colors": {
            "tertiary": "#bcc2ff",
            "tertiary-container": "#0021b9",
            "surface": "#131313",
            "on-primary-fixed": "#410000",
            "outline": "#a98984",
            "error": "#ffb4ab",
            "surface-tint": "#ffb4a8",
            "primary-fixed": "#ffdad4",
            "inverse-surface": "#e5e2e1",
            "surface-container-highest": "#353535",
            "error-container": "#93000a",
            "on-tertiary-fixed-variant": "#1830c2",
            "surface-container": "#20201f",
            "background": "#131313",
            "on-secondary-fixed": "#1e1b13",
            "inverse-primary": "#b22b1d",
            "inverse-on-surface": "#313030",
            "tertiary-fixed-dim": "#bcc2ff",
            "on-tertiary": "#001998",
            "secondary-fixed-dim": "#cdc6b8",
            "primary": "#ffb4a8",
            "on-tertiary-fixed": "#000c61",
            "on-tertiary-container": "#94a0ff",
            "on-primary": "#690000",
            "secondary-fixed": "#e9e2d4",
            "outline-variant": "#5a413d",
            "on-secondary": "#343027",
            "on-primary-fixed-variant": "#8f0f07",
            "on-secondary-fixed-variant": "#4b463c",
            "surface-variant": "#353535",
            "on-secondary-container": "#c2bbae",
            "on-surface": "#e5e2e1",
            "primary-container": "#800000",
            "surface-container-high": "#2a2a2a",
            "surface-bright": "#393939",
            "on-background": "#e5e2e1",
            "on-surface-variant": "#e2bfb9",
            "surface-container-low": "#1c1b1b",
            "on-error-container": "#ffdad6",
            "on-error": "#690005",
            "secondary-container": "#4f4b41",
            "tertiary-fixed": "#dfe0ff",
            "surface-dim": "#131313",
            "surface-container-lowest": "#0e0e0e",
            "secondary": "#cdc6b8",
            "on-primary-container": "#ff8371",
            "primary-fixed-dim": "#ffb4a8"
        },
        "borderRadius": {
            "DEFAULT": "0.25rem",
            "lg": "0.5rem",
            "xl": "0.75rem",
            "full": "9999px"
        },
        "spacing": {
            "sm": "1rem",
            "margin-desktop": "64px",
            "xs": "0.5rem",
            "xl": "4rem",
            "gutter": "24px",
            "base": "4px",
            "margin-mobile": "20px",
            "lg": "2.5rem",
            "md": "1.5rem"
        },
        "fontFamily": {
            "display-lg": ["Playfair Display"],
            "body-lg": ["Hanken Grotesk"],
            "caption": ["Hanken Grotesk"],
            "body-md": ["Hanken Grotesk"],
            "headline-lg-mobile": ["Playfair Display"],
            "headline-lg": ["Playfair Display"],
            "headline-md": ["Playfair Display"],
            "label-md": ["Hanken Grotesk"]
        },
        "fontSize": {
            "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
            "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
            "caption": ["12px", {"lineHeight": "1.4", "fontWeight": "400"}],
            "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
            "headline-lg-mobile": ["28px", {"lineHeight": "1.2", "fontWeight": "600"}],
            "headline-lg": ["32px", {"lineHeight": "1.2", "fontWeight": "600"}],
            "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "500"}],
            "label-md": ["14px", {"lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "600"}]
        }
    },
  },
  plugins: [],
}
